source ~/.config/zsh/prompt

autoload -U colors && colors

zstyle ':completion:*' matcher-list \
  '' \
  'm:{a-z}={A-Za-z}' \
  'm:{a-z}={A-Za-z} m:{a}={á} m:{e}={é} m:{i}={í} m:{o}={ó} m:{u}={ú} m:{u}={ü}'
zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"

eval "$(fzf --zsh)"

bindkey -e
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

HISTSIZE=5000
HISTFILE="$HOME/.zsh_history"
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

path+=("$HOME/dotfiles/scripts")
export PATH
export TERM=xterm-256color

alias l="ls -lh"
alias la="ls -lha"
alias v="nvim"
alias vi="nvim"
alias ".."="cd .."
alias ":q"="exit"

cr(){
  local pager content
  local opt OPTIND OPTARG

  while getopts 'p:h' opt; do
    case "$opt" in
      p) pager=$OPTARG ;;
      h) echo "Usage: cr [-p pager] [-h] url" ;;
      *) return 2 ;;
    esac
  done

  shift $((OPTIND - 1))

  [[ -z "$1" ]] && return 2

  content=$(curl "$1" 2>/dev/null)

  if [[ -n "$pager" ]]; then
    echo "$content" | $pager
  elif (($(echo "$content" | wc -l) > LINES - 4)); then
    echo "$content" | less
  else
    echo "$content"
  fi
}
