unbind C-b
set -g prefix º
bind º send-prefix

unbind l
unbind Up
unbind Down
unbind Right
unbind Left

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key s split-window -v -c "#{pane_current_path}"
bind-key v split-window -h -c "#{pane_current_path}"

bind-key & kill-window
bind-key x kill-pane

bind-key S display-popup -T "nvim─go─to" -E "~/dotfiles/scripts/nvim-go-to.sh"
bind-key Z display-popup -T "cd─go─to" -E "~/dotfiles/scripts/cd-go-to.sh"
bind-key A display-popup -T "cht.sh" -E "~/dotfiles/scripts/cht.sh"

set -a terminal-features "screen-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-position top
set -g status-style "bg=default"
set -g window-status-current-format "#[fg=blue bold]#I:#W"
set -g window-status-format "#I:#W"
set -g status-left ""
set -g status-right "#(~/dotfiles/scripts/battery.sh) #[fg=white]%d/%m/%y %H:%M"

set -g pane-border-style "fg=white"
set -g pane-active-border-style "fg=blue"

