# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle :compinstall filename '/home/sancho/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

autoload -U colors && colors

PROMPT="%B%F{#5c47c9}[%n@%m:%~]%b%f "

bindkey -e
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

path+=('/home/sancho/scripts')
export PATH

alias l="ls -lh"
alias la="ls -lha"
alias v="nvim"
alias vi="nvim"
alias ".."="cd .."
alias frf="nohup firefox >& /dev/null &"
alias ":q"="exit"
